-- ===============================================================================
-- Beim ALLERERSTEN Aufruf die Zeilen mit "DROP TABLE ..." durch -- auskommentieren
-- ===============================================================================
--DROP TABLE kunde;
--DROP TABLE adresse;
--DROP TABLE artikel;
--DROP TABLE bestellung;
--DROP TABLE bestellposition;
--DROP TABLE lieferant;